name: Build and Release

on:
    push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o gockerize-linux-amd64

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o gockerize-windows-amd64.exe

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }} for Linux and Windows
          draft: false
          prerelease: false

      - name: Upload Linux Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gockerize-linux-amd64
          asset_name: gockerize-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Windows Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gockerize-windows-amd64.exe
          asset_name: gockerize-windows-amd64.exe
          asset_content_type: application/octet-stream
